"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiFetch } from "@/lib/client-api";
import { slugify } from "@/lib/utils";

export default function SignupPage() {
  const router = useRouter();
  const [form, setForm] = useState({
    organisationName: "",
    organisationSlug: "",
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
  });
  const [slugEdited, setSlugEdited] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const generatedSlug = useMemo(() => slugify(form.organisationName), [form.organisationName]);

  useEffect(() => {
    if (slugEdited) {
      return;
    }
    if (form.organisationSlug !== generatedSlug) {
      setForm((prev) => ({ ...prev, organisationSlug: generatedSlug }));
    }
  }, [form.organisationSlug, generatedSlug, slugEdited]);

  async function onSubmit(event: FormEvent) {
    event.preventDefault();
    if (form.password !== form.confirmPassword) {
      setError("Passwords do not match");
      return;
    }

    setLoading(true);
    setError(null);
    const payload = {
      organisationName: form.organisationName.trim(),
      organisationSlug: form.organisationSlug.trim(),
      firstName: form.firstName.trim(),
      lastName: form.lastName.trim(),
      email: form.email.trim().toLowerCase(),
      password: form.password,
    };

    try {
      await apiFetch("/api/auth/signup", {
        method: "POST",
        body: JSON.stringify(payload),
      });
      router.push("/app/dashboard");
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create account");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen bg-gradient-to-br from-[#040812] via-[#0a1c33] to-[#0f2a4a] p-6">
      <div className="mx-auto max-w-2xl rounded-2xl border border-white/15 bg-slate-950/80 p-6 shadow-panel">
        <Image
          src="/branding/tradesflow_svg_bundle/tradesflow-logo-horizontal-light.svg"
          alt="TradesFlow"
          className="h-10 w-auto"
          width={200}
          height={40}
        />
        <h1 className="mt-4 font-display text-2xl font-semibold text-white">Create Contractor Workspace</h1>
        <p className="mt-1 text-sm text-slate-300">
          Launch your company tenant with owner access, branded defaults, and onboarding settings.
        </p>

        <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={onSubmit}>
          <label className="space-y-1 text-sm text-slate-200 sm:col-span-2">
            <span>Company Name</span>
            <Input
              value={form.organisationName}
              onChange={(event) => setForm((prev) => ({ ...prev, organisationName: event.target.value }))}
              className="bg-slate-900 text-white"
              required
            />
          </label>
          <label className="space-y-1 text-sm text-slate-200 sm:col-span-2">
            <span>Company Slug</span>
            <Input
              value={form.organisationSlug}
              onChange={(event) => {
                setSlugEdited(true);
                setForm((prev) => ({ ...prev, organisationSlug: slugify(event.target.value) }));
              }}
              placeholder="autogenerated-from-company-name"
              className="bg-slate-900 text-white"
            />
            <p className="text-xs text-slate-400">Used in workspace URLs. We auto-fill this and keep it unique.</p>
          </label>
          <label className="space-y-1 text-sm text-slate-200">
            <span>First Name</span>
            <Input
              value={form.firstName}
              onChange={(event) => setForm((prev) => ({ ...prev, firstName: event.target.value }))}
              className="bg-slate-900 text-white"
              required
            />
          </label>
          <label className="space-y-1 text-sm text-slate-200">
            <span>Last Name</span>
            <Input
              value={form.lastName}
              onChange={(event) => setForm((prev) => ({ ...prev, lastName: event.target.value }))}
              className="bg-slate-900 text-white"
              required
            />
          </label>
          <label className="space-y-1 text-sm text-slate-200 sm:col-span-2">
            <span>Email</span>
            <Input
              type="email"
              value={form.email}
              onChange={(event) => setForm((prev) => ({ ...prev, email: event.target.value }))}
              className="bg-slate-900 text-white"
              required
            />
          </label>
          <label className="space-y-1 text-sm text-slate-200 sm:col-span-2">
            <span>Password</span>
            <Input
              type="password"
              value={form.password}
              onChange={(event) => setForm((prev) => ({ ...prev, password: event.target.value }))}
              className="bg-slate-900 text-white"
              required
            />
          </label>
          <label className="space-y-1 text-sm text-slate-200 sm:col-span-2">
            <span>Confirm Password</span>
            <Input
              type="password"
              value={form.confirmPassword}
              onChange={(event) => setForm((prev) => ({ ...prev, confirmPassword: event.target.value }))}
              className="bg-slate-900 text-white"
              required
            />
          </label>
          {error ? <p className="sm:col-span-2 rounded-md bg-red-50 p-2 text-sm text-red-600">{error}</p> : null}
          <div className="sm:col-span-2 flex flex-wrap items-center justify-between gap-3">
            <Link href="/login" className="text-sm text-slate-400 hover:underline">
              Back to login
            </Link>
            <Button type="submit" disabled={loading}>
              {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
              Create workspace
            </Button>
          </div>
        </form>
      </div>
    </main>
  );
}
